In [2]:
import pandas as pd

In [55]:
df = pd.read_excel(r"V:\DEVELOPMENT_AID\__PROCESSING\checklist_r\2_functions\test_crstemplate_LT.xlsx", header=1)
df = df[1:].reset_index(drop=True)

In [ ]:
def check_crsid(df):
    controller=pd.DataFrame(df['CRS Identification N°'].value_counts()).reset_index(drop=False)
    controller.columns = ['CRS Identification N°', 'count']
    crs_id = []
    for i, row in controller.iterrows():
        if row["count"] > 1:
            crs_id.append(row['CRS Identification N°'])
    df.loc[df['CRS Identification N°'].isin(crs_id), 'errormessage'] += "Duplicate CRS ID; "
    return df

In [ ]:
check_crsid(df)

,errormessage,Reporting year,Commitment date (dd-mm-yyyy),Reporting country / organisation,Extending agency,CRS Identification N°,Donor project N°,Nature of submission,Recipient code,Channel of delivery name,Channel code,Bi/Multi,Type of flow (main DAC 1 category),Type of finance,Co-operation modality (replaces the type of aid),Short description / Project title,Sector / Purpose code and corresponding shares,Geographical target area,Regional aid to LDCs (codes 1-5),Expected starting date,Expected completion date,Description,SDG focus*,Keywords*,Gender equality,Aid to environment,DIG,RMNCH,Disaster Risk Reduction,Nutrition*,Inclusion and empowerment of persons with disabilities*,FTC,PBA,Investment,Type of blended finance (codes 1-4),Biodiversity,Climate change - mitigation,Climate change - adaptation,Desertification,Currency,Commitments,Capital Expenditure %*,Amounts extended,ODA grant equivalent,Amounts received (for loans:principal only),Amount untied,Amount partially untied,Amount tied,Amount of IRTC,"If project type, amount of experts-commitments*","If project type, amount of experts-extended*",Amount of export credit,Leveraging mechanism and role/position,Amounts mobilised from the private sector,Origin of the funds mobilised,Type or repayment \nor type of fee payment,Number of repayment \nor fee payment per annum,Interest rate /\n Fee rate /\nExpected return per annum,Second interest rate,First repayment date /\nExposure reduction starting date \n(dd-mm-yyyy),Final repayment date / \nGuarantee maturity date / \nExpected maturity \n(dd-mm-yyyy),Interest received / \nGuarantee fee received / \nDividends received per annum,Principal disbursed and still outstanding / \nEquity disbursed and still held,Arrears of principal (included in the item 62),Arrears of interest / \nArrears of guarantee fee,Guaranteed amount,Average use of portfolio guarantee %,PSI flag,Additionality type,Additionality assessment,Additionality – development objective,Income Group,Discount Rate,Grant Element
0,Duplicate CRS ID; Duplicate CRS ID;,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,3000,African Development Bank,12004.0,2.0,10,420,NaN,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Duplicate CRS ID; Duplicate CRS ID;,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,12004.0,2.0,10,420,NaN,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Duplicate CRS ID; Duplicate CRS ID;,2024,2024-01-15 00:00:00,1,1,20220000002,abcd,1,249,International Committee of the Red Cross,NaN,8.0,10,110,A02,Programme d'agriculture durable et de sécurité...,99810,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,,2024,2021-12-31 00:00:00,1,1,20220000003,abcd,3,998,Institute for Advanced Research and Policy Stu...,51010.0,4.0,10,110,A02,Education for All: Inclusive Learning Environm...,42559;12264,"Himalayan Mountain Range, Nepal",NaN,NaN,NaN,The objective of this project is to ensure acc...,5.a;5.b,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0,2,302,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,,2024,2024-01-01 00:00:00,1,1,20220000004,abcd,1,998,Republic of Ireland,12003.0,8.0,21,420,NaN,Clean Water and Sanitation for Communities,41000,"Great Rift Valley, Kenya",NaN,NaN,NaN,This project aims to provide clean and safe dr...,5,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2,820,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Duplicate CRS ID; Duplicate CRS ID;,2024,2024-01-01 00:00:00,7000,1,20220000005,abcd,8,998,Private sector partnership with local small an...,21045.0,3.0,10,110,B01,Renewable Energy for Sustainable Development,23231,NaN,NaN,NaN,NaN,This project focuses on increasing access to r...,NaN,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,62,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Duplicate CRS ID; Duplicate CRS ID;,2024,2024-01-01 00:00:00,1,1,20220000005,abcd,8,998,Private sector partnership with local small an...,NaN,3.0,10,110,B01,Vedvarende energi til bæredygtig udvikling,45866,"Ganges River Delta, Bangladesh",4.0,NaN,NaN,This project focuses on increasing access to r...,1;2;3;4;5;6;7;8;9;10;11,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,62,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Duplicate CRS ID; Duplicate CRS ID;,2024,NaN,1,1,20220000002,abcd,1,998,International Committee of the Red Cross,47035.0,7.0,60,600,NaN,Este proyecto pretende promover prácticas agrí...,43060,NaN,NaN,NaN,NaN,This project seeks to promote sustainable agri...,NaN,NaN,2,2.0,2.0,2.0,0.0,2.0,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Duplicate CRS ID; Duplicate CRS ID;,2024,2023-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,30015.0,2.0,10,420,B01,Rural Healthcare Enhancement Initiative,51010:19.5|45866:30|51010:50.5,NaN,NaN,NaN,NaN,The initiative will focus on maternal and chil...,13,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Duplicate CRS ID; Duplicate CRS ID;,2024,2022-01-15 00:00:00,1,1,20220000002,abcd,1,249,International Committee of the Red Cross,21009.0,7.0,10,110,B01,Programme d'agriculture durable et de sécurité...,12240,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Duplicate CRS ID; Duplicate CRS ID;,2024,2022-01-15 00:00:00,1,1,20220000002,abcd,1,249,International Committee of the Red Cross,21009.0,7.0,10,110,A01,Programme d'agriculture durable et de sécurité...,12240:100,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Duplicate CRS ID; Duplicate CRS ID;,2024,2022-01-15 00:00:00,1,1,20220000002,abcd,1,3000,International Committee of the Red Cross,21009.0,7.0,10,110,A01,Programme d'agriculture durable et de sécurité...,12240:100,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Duplicate CRS ID; Duplicate CRS ID;,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,12004.0,8.0,10,420,B02,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Duplicate CRS ID; Duplicate CRS ID;,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,12004.0,2.0,10,420,B02,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Duplicate CRS ID; Duplicate CRS ID;,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,12004.0,2.0,10,420,NaN,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Duplicate CRS ID; Duplicate CRS ID;,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,12004.0,9.0,10,420,H02,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Duplicate CRS ID; Duplicate CRS ID;,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,85,African Development Bank,12004.0,1.0,10,420,H01,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Duplicate CRS ID; Duplicate CRS ID;,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,1,African Development Bank,12004.0,NaN,10,420,H06,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [110]:
df.head()

,errormessage,Reporting year,Commitment date (dd-mm-yyyy),Reporting country / organisation,Extending agency,CRS Identification N°,Donor project N°,Nature of submission,Recipient code,Channel of delivery name,Channel code,Bi/Multi,Type of flow (main DAC 1 category),Type of finance,Co-operation modality (replaces the type of aid),Short description / Project title,Sector / Purpose code and corresponding shares,Geographical target area,Regional aid to LDCs (codes 1-5),Expected starting date,Expected completion date,Description,SDG focus*,Keywords*,Gender equality,Aid to environment,DIG,RMNCH,Disaster Risk Reduction,Nutrition*,Inclusion and empowerment of persons with disabilities*,FTC,PBA,Investment,Type of blended finance (codes 1-4),Biodiversity,Climate change - mitigation,Climate change - adaptation,Desertification,Currency,Commitments,Capital Expenditure %*,Amounts extended,ODA grant equivalent,Amounts received (for loans:principal only),Amount untied,Amount partially untied,Amount tied,Amount of IRTC,"If project type, amount of experts-commitments*","If project type, amount of experts-extended*",Amount of export credit,Leveraging mechanism and role/position,Amounts mobilised from the private sector,Origin of the funds mobilised,Type or repayment \nor type of fee payment,Number of repayment \nor fee payment per annum,Interest rate /\n Fee rate /\nExpected return per annum,Second interest rate,First repayment date /\nExposure reduction starting date \n(dd-mm-yyyy),Final repayment date / \nGuarantee maturity date / \nExpected maturity \n(dd-mm-yyyy),Interest received / \nGuarantee fee received / \nDividends received per annum,Principal disbursed and still outstanding / \nEquity disbursed and still held,Arrears of principal (included in the item 62),Arrears of interest / \nArrears of guarantee fee,Guaranteed amount,Average use of portfolio guarantee %,PSI flag,Additionality type,Additionality assessment,Additionality – development objective,Income Group,Discount Rate,Grant Element
0,Duplicate CRS ID;,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,3000,African Development Bank,12004.0,2.0,10,420,NaN,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Duplicate CRS ID;,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,12004.0,2.0,10,420,NaN,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Duplicate CRS ID;,2024,2024-01-15 00:00:00,1,1,20220000002,abcd,1,249,International Committee of the Red Cross,NaN,8.0,10,110,A02,Programme d'agriculture durable et de sécurité...,99810,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,,2024,2021-12-31 00:00:00,1,1,20220000003,abcd,3,998,Institute for Advanced Research and Policy Stu...,51010.0,4.0,10,110,A02,Education for All: Inclusive Learning Environm...,42559;12264,"Himalayan Mountain Range, Nepal",NaN,NaN,NaN,The objective of this project is to ensure acc...,5.a;5.b,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0,2,302,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,,2024,2024-01-01 00:00:00,1,1,20220000004,abcd,1,998,Republic of Ireland,12003.0,8.0,21,420,NaN,Clean Water and Sanitation for Communities,41000,"Great Rift Valley, Kenya",NaN,NaN,NaN,This project aims to provide clean and safe dr...,5,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2,820,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN