In [18]:
import pandas as pd
import pyreadr

In [19]:
df = pd.read_excel(r"\\main.oecd.org\ASgenDCD\DEVELOPMENT_AID\__PROCESSING\checklist_r\2_functions\test_crstemplate_GG.xlsx",header = 1)
df_lookup = pyreadr.read_r(r"\\main.oecd.org\ASgenDCD\DEVELOPMENT_AID\__PROCESSING\checklist_r\3_share\lookups_checklist.RData")
df = df.loc[1:].reset_index(drop=True) #we drop the row with the number (2nd row = index 1)
df["error_message"] = ""
df["warning_message"] = ""

In [20]:
df_lookup.keys()

odict_keys(['aid_t_list', 'annex2_lookup', 'channels_list', 'currency_list', 'donor_agency_lookup', 'donor_countries', 'finance_list', 'list_guarantees', 'long_channels_list', 'lookup_donor', 'multilateral_donors', 'parent_channel_lookup', 'private_donors', 'purposes_list', 'recipients_list', 'regional_recipients'])

In [21]:
df_finance = df_lookup["finance_list"]

In [22]:
df_finance

    finance_list
0              0
1              1
2              2
3              3
4              4
..           ...
86          1106
87          1107
88          1108
89          4221
90          4222

[91 rows x 1 columns]

In [23]:
df.columns

Index(['Reporting year', 'Commitment date (dd-mm-yyyy)',
       'Reporting country / organisation', 'Extending agency',
       'CRS Identification N°', 'Donor project N°', 'Nature of submission',
       'Recipient code', 'Channel of delivery name', 'Channel code',
       'Bi/Multi', 'Type of flow (main DAC 1 category)', 'Type of finance',
       'Co-operation modality (replaces the type of aid)',
       'Short description / Project title',
       'Sector / Purpose code and corresponding shares',
       'Geographical target area', 'Regional aid to LDCs (codes 1-5)',
       'Expected starting date ', 'Expected completion date', 'Description',
       'SDG focus*', 'Keywords*', 'Gender equality', 'Aid to environment',
       'DIG', 'RMNCH', 'Disaster Risk Reduction', 'Nutrition*',
       'Inclusion and empowerment of persons with disabilities*', 'FTC', 'PBA',
       'Investment', 'Type of blended finance (codes 1-4) ', 'Biodiversity',
       'Climate change - mitigation', 'Climate change - adaptation',
       'Desertification', 'Currency', 'Commitments', 'Capital Expenditure %*',
       'Amounts extended', 'ODA grant equivalent',
       ' Amounts received (for loans:principal only)', 'Amount untied',
       'Amount partially untied', 'Amount tied', 'Amount of IRTC',
       'If project type, amount of experts-commitments*',
       'If project type, amount of experts-extended*',
       'Amount of export credit', 'Leveraging mechanism and role/position',
       'Amounts mobilised from the private sector',
       'Origin of the funds mobilised',
       'Type or repayment \nor type of fee payment',
       'Number of repayment \nor fee payment per annum',
       'Interest rate /\n Fee rate /\nExpected return per annum',
       'Second interest rate',
       'First repayment date /\nExposure reduction starting date \n(dd-mm-yyyy)',
       'Final repayment date / \nGuarantee maturity date / \nExpected maturity \n(dd-mm-yyyy)',
       'Interest received / \nGuarantee fee received / \nDividends received per annum',
       'Principal disbursed and still outstanding / \nEquity disbursed and still held',
       'Arrears of principal (included in the item 62)',
       'Arrears of interest / \nArrears of guarantee fee', 'Guaranteed amount',
       'Average use of portfolio guarantee %', 'PSI flag',
       'Additionality type', 'Additionality assessment',
       'Additionality – development objective', 'Income Group ',
       'Discount Rate', 'Grant Element', 'error_message', 'warning_message'],
      dtype='object')

In [28]:
df.loc[~df["Type of finance"].isin(df_finance["finance_list"]), "error_message"]+= " ;Invalid entry for type of finance, please consult the code list for the list of finance types"

In [29]:
df["error_message"]

0
1
2      ;Invalid entry for type of finance, please co...
3
4
5
6
7
8
9
10     ;Invalid entry for type of finance, please co...
11
12
13
Name: error_message, dtype: object

In [34]:
df["error_message"]+=df["CRS Identification N°"].duplicated(keep=False).map(lambda x:" .Duplicate CRS ID" if x else"")

In [38]:
df[["CRS Identification N°","error_message"]]

    CRS Identification N°                                      error_message
0             20220000001                                  .Duplicate CRS ID
1             20220000002                                  .Duplicate CRS ID
2             20220000003   ;Invalid entry for type of finance, please co...
3             20220000004
4             20220000005                                  .Duplicate CRS ID
5             20220000005                                  .Duplicate CRS ID
6             20220000002                                  .Duplicate CRS ID
7             20220000001                                  .Duplicate CRS ID
8             20220000002                                  .Duplicate CRS ID
9             20220000002                                  .Duplicate CRS ID
10            20220000002   ;Invalid entry for type of finance, please co...
11            20220000001                                  .Duplicate CRS ID
12            20220000001                                  .Duplicate CRS ID
13            20220000001                                  .Duplicate CRS ID