In [1]:
"""


# Column 22: SDGs ---------------------------------------------------------
## Is it correct that only 10 SDGs can be reported in CRS??

check_sdgs <- function(df) {
  df %>%  
    ## Check that cell doesn't contain any characters besides digits, semicolons, periods and the letters a-d
    mutate(errormessage = case_when(str_detect(sdg_focus,"[^\\d;.abcd ]") ~ paste0(errormessage,"Incorrect formatting of SDGs - please verify that all SDGs are written in numeric format and separated by a semi-colon; "),
                                    TRUE ~ errormessage)) %>%  
    ## Check that no more than 10 SDGs are reported
    mutate(errormessage = case_when(str_count(sdg_focus, ";") > 9 ~ paste0(errormessage,"A maximum of 10 SDG focuses can be reported per activity; "),
                                    TRUE ~ errormessage)) %>% 
    rowwise() %>% 
    mutate(errormessage = {

      sdgs <- str_split(sdg_focus,";") # Splits SDG fields into a list
      
      for (i in seq_along(sdgs)) {
        if (length(sdgs[[i]]) > 1 && any(duplicated(sdgs[[i]]))) {
          errormessage <- paste0(errormessage, "Duplicate SDG focus - each SDG can only be reported once per activity; ")
          break  # Stop checking further once a duplicate is found
        }
      }
      
      errormessage
    }) %>% 
    ungroup()
}
"""

'\n\n\n# Column 22: SDGs ---------------------------------------------------------\n## Is it correct that only 10 SDGs can be reported in CRS??\n\ncheck_sdgs <- function(df) {\n  df %>%  \n    ## Check that cell doesn\'t contain any characters besides digits, semicolons, periods and the letters a-d\n    mutate(errormessage = case_when(str_detect(sdg_focus,"[^\\d;.abcd ]") ~ paste0(errormessage,"Incorrect formatting of SDGs - please verify that all SDGs are written in numeric format and separated by a semi-colon; "),\n                                    TRUE ~ errormessage)) %>%  \n    ## Check that no more than 10 SDGs are reported\n    mutate(errormessage = case_when(str_count(sdg_focus, ";") > 9 ~ paste0(errormessage,"A maximum of 10 SDG focuses can be reported per activity; "),\n                                    TRUE ~ errormessage)) %>% \n    rowwise() %>% \n    mutate(errormessage = {\n\n      sdgs <- str_split(sdg_focus,";") # Splits SDG fields into a list\n\n      for (i in seq_along(sdgs)) {\n        if (length(sdgs[[i]]) > 1 && any(duplicated(sdgs[[i]]))) {\n          errormessage <- paste0(errormessage, "Duplicate SDG focus - each SDG can only be reported once per activity; ")\n          break  # Stop checking further once a duplicate is found\n        }\n      }\n\n      errormessage\n    }) %>% \n    ungroup()\n}\n'

In [28]:
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 500)

In [29]:
import pandas as pd

In [30]:
df = pd.read_excel(r"V:\DEVELOPMENT_AID\__PROCESSING\checklist_r\2_functions\test_crstemplate_LT.xlsx", header=1)
df = df[1:].reset_index(drop=True)

In [56]:
df["errormessage"] = ""

In [32]:
df.head()

,Reporting year,Commitment date (dd-mm-yyyy),Reporting country / organisation,Extending agency,CRS Identification N°,Donor project N°,Nature of submission,Recipient code,Channel of delivery name,Channel code,Bi/Multi,Type of flow (main DAC 1 category),Type of finance,Co-operation modality (replaces the type of aid),Short description / Project title,Sector / Purpose code and corresponding shares,Geographical target area,Regional aid to LDCs (codes 1-5),Expected starting date,Expected completion date,Description,SDG focus*,Keywords*,Gender equality,Aid to environment,DIG,RMNCH,Disaster Risk Reduction,Nutrition*,Inclusion and empowerment of persons with disabilities*,FTC,PBA,Investment,Type of blended finance (codes 1-4),Biodiversity,Climate change - mitigation,Climate change - adaptation,Desertification,Currency,Commitments,Capital Expenditure %*,Amounts extended,ODA grant equivalent,Amounts received (for loans:principal only),Amount untied,Amount partially untied,Amount tied,Amount of IRTC,"If project type, amount of experts-commitments*","If project type, amount of experts-extended*",Amount of export credit,Leveraging mechanism and role/position,Amounts mobilised from the private sector,Origin of the funds mobilised,Type or repayment \nor type of fee payment,Number of repayment \nor fee payment per annum,Interest rate /\n Fee rate /\nExpected return per annum,Second interest rate,First repayment date /\nExposure reduction starting date \n(dd-mm-yyyy),Final repayment date / \nGuarantee maturity date / \nExpected maturity \n(dd-mm-yyyy),Interest received / \nGuarantee fee received / \nDividends received per annum,Principal disbursed and still outstanding / \nEquity disbursed and still held,Arrears of principal (included in the item 62),Arrears of interest / \nArrears of guarantee fee,Guaranteed amount,Average use of portfolio guarantee %,PSI flag,Additionality type,Additionality assessment,Additionality – development objective,Income Group,Discount Rate,Grant Element,errormessage
0,2024,2022-01-15 00:00:00,1,1,20220000001a,abcd,1,3000,African Development Bank,12004.0,2.0,10,420,NaN,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
1,2024,2022-01-15 00:00:00,1,1,20220000001a,abcd,1,998,African Development Bank,12004.0,2.0,10,420,NaN,Rural Healthcare Enhancement Initiative,51010:20.12|45866:30|99810:40,"Amazon Rainforest, Brazil",NaN,NaN,NaN,This project aims to improve healthcare servic...,5;1.2,NaN,1,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,1.0,1.0,1,1,3,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
2,2024,2024-01-15 00:00:00,1,1,20220000002,abcd,1,249,International Committee of the Red Cross,NaN,8.0,10,110,A02,Programme d'agriculture durable et de sécurité...,99810,"The Mekong Delta region in Vietnam, which is a...",3.0,NaN,NaN,This project seeks to promote sustainable agri...,1.2|1.4,NaN,2,2.0,2.0,2.0,2.0,2.0,2.0,NaN,NaN,NaN,NaN,2.0,2.0,2,2,75,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
3,2024,2021-12-31 00:00:00,1,1,20220000003,abcd,3,998,Institute for Advanced Research and Policy Stu...,51010.0,4.0,10,110,A02,Education for All: Inclusive Learning Environm...,42559;12264,"Himalayan Mountain Range, Nepal",NaN,NaN,NaN,The objective of this project is to ensure acc...,5.a;5.b,NaN,0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,0.0,0.0,0,2,302,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,
4,2024,2024-01-01 00:00:00,1,1,20220000004,abcd,1,998,Republic of Ireland,12003.0,8.0,21,420,NaN,Clean Water and Sanitation for Communities,41000,"Great Rift Valley, Kenya",NaN,NaN,NaN,This project aims to provide clean and safe dr...,5,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,2,820,NaN,NaN,10000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,

In [34]:
sdg_df = pd.read_excel(r"C:\SmartData\repos\tor_fileuploader\sdg_lookup.xlsx")

In [35]:
list_sdgs = list(sdg_df.Target)

In [ ]:
def check_sdg(df):
    import re

    df["SDG focus*"] = df["SDG focus*"].astype(str)

    def check_row(row):
        errormessage = row['errormessage']
        sdg_focus = row['SDG focus*']
        

        # Check for incorrect formatting

        if re.search(r'[^\\d;. ]', sdg_focus):
    
        # if re.search(r'[^\\d;.abcd ]', sdg_focus):
        #     errormessage += "Incorrect formatting of SDGs - please verify that all SDGs are written in numeric format and separated by a semi-colon; "
    
        # Check for duplicate SDGs
        if sdg_focus.str.contains(';').any():
            sdgs = sdg_focus.split(';')

            if len(sdgs) != len(set(sdgs)):
                errormessage += "Duplicate SDG focus - each SDG can only be reported once per activity; "

            if set(sdgs).issubset(list_sdgs):
                pass
            else : 
                errormessage += "SDG focus not in list of valid SDGs; "

                    # Check for more than 10 SDGs
            if sdg_focus.count(';') > 9:
                 errormessage += "A maximum of 10 SDG focuses can be reported per activity; "

        return errormessage

    df['errormessage'] = df.apply(check_row, axis=1)
    return df

In [58]:
df_checked = check_sdg(df)
df_checked[['SDG focus*', 'errormessage']].head(20)

                 SDG focus*                                       errormessage
0                     5;1.2
1                     5;1.2
2                   1.2|1.4              SDG focus not in list of valid SDGs;
3                   5.a;5.b
4                         5
5                       nan              SDG focus not in list of valid SDGs;
6   1;2;3;4;5;6;7;8;9;10;11  A maximum of 10 SDG focuses can be reported pe...
7                       nan              SDG focus not in list of valid SDGs;
8                        13
9                   1.2|1.4              SDG focus not in list of valid SDGs;
10                  1.2|1.4              SDG focus not in list of valid SDGs;
11                  1.2|1.4              SDG focus not in list of valid SDGs;
12                    5;1.2
13                    5;1.2
14                    5;1.2
15                    5;1.2
16                    5;1.2
17                    5;1.2

In [38]:
test = "5.a;5.b"

In [40]:
test.split(';')

['5.a', '5.b']

In [41]:
test_list = test.split(';')

In [55]:
#output_list = filter( lambda x: isinstance(x,list_sdgs), test_list)

if set(test_list).issubset(list_sdgs):
    print("Yes")
else:
    print("No")

Yes

In [ ]:
output_list = filter( lambda x: isinstance(x,list), input_list)