## Catch-up Python training session - August 20th - Aid_t

In [1]:
import pandas as pd

In [5]:
df = pd.read_excel(r"\\main.oecd.org\ASgenDCD\DEVELOPMENT_AID\__PROCESSING\checklist_r\2_functions\test_crstemplate_GG.xlsx",header = 1)
df = df.loc[1:].reset_index(drop=True)

In [6]:
df.head()

,Reporting year,Commitment date (dd-mm-yyyy),Reporting country / organisation,Extending agency,CRS Identification N°,Donor project N°,Nature of submission,Recipient code,Channel of delivery name,Channel code,...,Arrears of interest / \nArrears of guarantee fee,Guaranteed amount,Average use of portfolio guarantee %,PSI flag,Additionality type,Additionality assessment,Additionality – development objective,Income Group,Discount Rate,Grant Element
0,2024,2022-01-15 00:00:00,1,1,20220000001,abcd,1,998,African Development Bank,12004.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024,2024-01-15 00:00:00,1,1,20220000002,abcd,1,249,International Committee of the Red Cross,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2024,2021-12-31 00:00:00,1,1,20220000003,abcd,3,998,Institute for Advanced Research and Policy Stu...,51010.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2024,2024-01-01 00:00:00,1,1,20220000004,abcd,1,998,Republic of Ireland,12003.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,2024-01-01 00:00:00,7000,1,20220000005,abcd,8,998,Private sector partnership with local small an...,21045.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
for i,  row in df.iterrows():
    print(i)

0
1
2
3
4
5
6
7
8

In [ ]:
df["errormessage"]= "" #Initialize the error message column
df["warningmessage"]= "" #Initialize the error message column

for i, row in df.iterrows():
    if ( row["Type of flow (main DAC 1 category)"]==10 or row["Type of flow (main DAC 1 category)"]==21 or row["Type of flow (main DAC 1 category)"]==60 ) & (pd.isna(row["Co-operation modality (replaces the type of aid)"])):
        df.loc[i,"errormessage"]= df.loc[i,"errormessage"]+"; ""Co-operation modality (replaces the type of aid) is missing for this type of flow"
        
    if ( row["Type of flow (main DAC 1 category)"]==10 or row["Type of flow (main DAC 1 category)"]==21 or row["Type of flow (main DAC 1 category)"]==60 ) & (row["Co-operation modality (replaces the type of aid)"]=="A01") & (~row["Sector / Purpose code and corresponding shares"].str.contains("51010")):
        df.loc[i,"errormessage"]= df.loc[i,"warningmessage"]+"; ""Purpose code should be 51010 when co-operation modality is A01"

In [47]:
df["Co-operation modality (replaces the type of aid)"].isna().sum() # Count of missing values in the specified column

3

In [48]:
df[["Type of flow (main DAC 1 category)","Co-operation modality (replaces the type of aid)","errormessage","warningmessage"]].head()

,Type of flow (main DAC 1 category),Co-operation modality (replaces the type of aid),errormessage,warningmessage
0,10,NaN,; Co-operation modality (replaces the type of ...,
1,10,A02,,
2,10,A02,,
3,21,NaN,; Co-operation modality (replaces the type of ...,
4,10,B01,,

In [38]:
df.loc[3,"errormessage"]

'Co-operation modality (replaces the type of aid) is missing for this type of flow'